development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:623a5edfaedf584160ac7269cd1489ef@greeneye.redistogo.com:9598/
  # channel_prefix: message-me_production
